[package]
name = "assembler"
version = "0.1.0"
edition.workspace = true

[dependencies]
phf = { version = "0.13.1", features = ["macros"] }
srec = "0.2.0"
ariadne = "0.6.0"
tempfile = "3.23.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
